In [ ]:
pip install networkx

In [1]:
import pandas as pd 
import numpy as np
import networkx as nx
import sys
from sklearn.cluster import SpectralClustering
import matplotlib.pyplot as plt

In [ ]:
def abundance_to_edge_list(df):
    
    df_list = []
    for index, rows in df_new.iterrows():
        df_list.append
        
    stacked_df_values = df_new.stack()
    final_df = pd.DataFrame(stacked_df_values, columns=["destination","values"])
    final_df = final_df.reset_index()
    final_df = final_df.rename(columns = {"level_0":"p_id", "level_1":"mp_id"})
    final_df["p_id"] = final_df["p_id"] +1

In [3]:
df_sample = pd.read_csv('mp_samples.csv')
df_sample.head()

Patients  p_id   1  2   3  4  5  6  7  8  ...  2960  2961  2962  2963  2964  \
0    P01_C     1  25  0  98  0  0  0  0  0  ...     0     0     0     0    16   
1    P02_C     2   0  0   0  0  0  0  0  0  ...     0     0     0     0    11   
2    P03_C     3  96  2  19  0  0  0  0  0  ...     0     0     0     0     9   
3    P04_C     4   0  0  16  0  0  0  0  0  ...     0     0     0     0    12   
4    P05_C     5   0  0   0  0  0  0  0  0  ...     0     0     0     0     9   

   2965  2966  2967  2968  2969  
0     0     0     0     1    31  
1     0     0     0     0     0  
2     0     0     0     0     0  
3     0     0     0     0     0  
4     0     0     0     0     0  

[5 rows x 2971 columns]

In [4]:
df_new = df_sample.iloc[:, 2:]
df_list = []
for index, rows in df_new.iterrows():
    df_list.append

In [5]:
stacked_df_values = df_new.stack()
print(type(stacked_df_values))

<class 'pandas.core.series.Series'>


In [6]:
final_df = pd.DataFrame(stacked_df_values, columns=["destination","values"])
final_df.index

ValueError: Shape of passed values is (142512, 1), indices imply (142512, 2)

In [7]:
final_df = final_df.reset_index()

NameError: name 'final_df' is not defined

In [ ]:
final_df = final_df.rename(columns = {"level_0":"p_id", "level_1":"mp_id"})

In [ ]:
final_df

In [ ]:
final_df["p_id"] = final_df["p_id"] +1

In [ ]:
final_df

In [2]:
df_csv = pd.read_csv("mp_samples.csv")
df_csv.head()

Patients  p_id   1  2   3  4  5  6  7  8  ...  2960  2961  2962  2963  2964  \
0    P01_C     1  25  0  98  0  0  0  0  0  ...     0     0     0     0    16   
1    P02_C     2   0  0   0  0  0  0  0  0  ...     0     0     0     0    11   
2    P03_C     3  96  2  19  0  0  0  0  0  ...     0     0     0     0     9   
3    P04_C     4   0  0  16  0  0  0  0  0  ...     0     0     0     0    12   
4    P05_C     5   0  0   0  0  0  0  0  0  ...     0     0     0     0     9   

   2965  2966  2967  2968  2969  
0     0     0     0     1    31  
1     0     0     0     0     0  
2     0     0     0     0     0  
3     0     0     0     0     0  
4     0     0     0     0     0  

[5 rows x 2971 columns]

In [3]:
df_csv_data = df_csv.iloc[:, 2:2971]
df_csv_data.head()

1  2   3  4  5  6  7  8  9  10  ...  2960  2961  2962  2963  2964  2965  \
0  25  0  98  0  0  0  0  0  0   0  ...     0     0     0     0    16     0   
1   0  0   0  0  0  0  0  0  0   0  ...     0     0     0     0    11     0   
2  96  2  19  0  0  0  0  0  0   3  ...     0     0     0     0     9     0   
3   0  0  16  0  0  0  0  0  0   0  ...     0     0     0     0    12     0   
4   0  0   0  0  0  0  0  0  0   0  ...     0     0     0     0     9     0   

   2966  2967  2968  2969  
0     0     0     1    31  
1     0     0     0     0  
2     0     0     0     0  
3     0     0     0     0  
4     0     0     0     0  

[5 rows x 2969 columns]

In [4]:
df_graph = pd.read_csv("graph.csv")
df_graph.head()

Unnamed: 0  sid  values           class   did              family  \
0           0    1       0        Mammalia   382           Hominidae   
1           1    1       0        Mammalia  2881           Hominidae   
2           2    1       2      unassigned  2787          unassigned   
3           3    1       0  Actinobacteria  2688  Bifidobacteriaceae   
4           4    1       0     Bacteroidia  2589      Bacteroidaceae   

               order            genus          phylum     kingdom  \
0           Primates             Homo        Chordata     Metazoa   
1           Primates             Homo        Chordata     Metazoa   
2         unassigned       unassigned        Chordata     Metazoa   
3  Bifidobacteriales  Bifidobacterium  Actinobacteria  unassigned   
4      Bacteroidales      Bacteroides   Bacteroidetes  unassigned   

                                         metaprotein  \
0  CATG_HUMAN Cathepsin G OS=Homo sapiens GN=CTSG...   
1  RP1L1_HUMAN Retinitis pigmentosa 1-like 1 prot...   
2  TTHY_PANTR Transthyretin OS=Pan troglodytes GN...   
3  TIG_BIFAA Trigger factor OS=Bifidobacterium ad...   
4  SUSC_BACTN TonB-dependent receptor SusC OS=Bac...   

                        species superkingdom  
0                  Homo sapiens    Eukaryota  
1                  Homo sapiens    Eukaryota  
2                    unassigned    Eukaryota  
3                    unassigned     Bacteria  
4  Bacteroides thetaiotaomicron     Bacteria

In [5]:
df_graph.shape

(142512, 13)

In [6]:
df_adjacency_matrix = df_graph[['sid', 'did', 'values']]
df_adjacency_matrix.head()

sid   did  values
0    1   382       0
1    1  2881       0
2    1  2787       2
3    1  2688       0
4    1  2589       0

In [7]:
df_adjacency_matrix['sid'] = 'p' + df_adjacency_matrix['sid'].astype(str)
df_adjacency_matrix['did'] = 'mp' + df_adjacency_matrix['did'].astype(str)
df_adjacency_matrix

C:\Users\49171\AppData\Local\Temp\ipykernel_7728\4102056461.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_adjacency_matrix['sid'] = 'p' + df_adjacency_matrix['sid'].astype(str)
C:\Users\49171\AppData\Local\Temp\ipykernel_7728\4102056461.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_adjacency_matrix['did'] = 'mp' + df_adjacency_matrix['did'].astype(str)


sid     did  values
0        p1   mp382       0
1        p1  mp2881       0
2        p1  mp2787       2
3        p1  mp2688       0
4        p1  mp2589       0
...     ...     ...     ...
142507  p48   mp178       5
142508  p48   mp266       0
142509  p48   mp420       0
142510  p48   mp165       0
142511  p48   mp323       0

[142512 rows x 3 columns]

In [8]:
# values_list = df_adjacency_matrix[["values"]]
# values_dict = dict.fromkeys(range(len(df_adjacency_matrix)), values_list)
# values_dict

In [9]:
# values_array = df_adjacency_matrix[["values"]].to_numpy()
# values_array
# values_array.shape

In [10]:
# adjacency_matrix = pd.crosstab(df_adjacency_matrix.sid, df_adjacency_matrix.did, values = values_array, 
#                                aggfunc = "count")
# idx = adjacency_matrix.columns.union(adjacency_matrix.index)
# adjacency_matrix = adjacency_matrix.reindex(index = idx, columns=idx, fill_value=0)

In [11]:
# adjacency_matrix

In [12]:
values_list = df_adjacency_matrix.values.tolist()
G = nx.DiGraph()

for i in range(len(values_list)):
    G.add_edge(values_list[i][0], values_list[i][1], weight=values_list[i][2])
    
# G = nx.from_pandas_edgelist(df_adjacency_matrix, 'sid', 'did', ['values'], create_using=nx.DiGraph())
# adj_mat = nx.to_pandas_adjacency(G, dtype=int)

adj_mat = nx.adjacency_matrix(G).A


C:\Users\49171\AppData\Local\Temp\ipykernel_7728\3487469263.py:10: FutureWarning: adjacency_matrix will return a scipy.sparse array instead of a matrix in Networkx 3.0.
  adj_mat = nx.adjacency_matrix(G).A


In [13]:
# adj_mat = nx.adjacency_matrix(G).A
adj_mat

array([[ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       ...,
       [ 0, 34,  0, ...,  0,  0,  0],
       [ 0, 10,  0, ...,  0,  0,  0],
       [ 0, 13,  0, ...,  0,  0,  0]], dtype=int32)

In [19]:
adj_mat.shape

(3017, 3017)

In [14]:
aff_mat = nx.to_scipy_sparse_matrix(G)

C:\Users\49171\AppData\Local\Temp\ipykernel_7728\4138629699.py:1: DeprecationWarning: 

The scipy.sparse array containers will be used instead of matrices
in Networkx 3.0. Use `to_scipy_sparse_array` instead.
  aff_mat = nx.to_scipy_sparse_matrix(G)


In [15]:
print(aff_mat)

  (0, 1)	0
  (0, 2)	0
  (0, 3)	2
  (0, 4)	0
  (0, 5)	0
  (0, 6)	0
  (0, 7)	0
  (0, 8)	0
  (0, 9)	0
  (0, 10)	0
  (0, 11)	0
  (0, 12)	0
  (0, 13)	0
  (0, 14)	0
  (0, 15)	0
  (0, 16)	0
  (0, 17)	0
  (0, 18)	0
  (0, 19)	0
  (0, 20)	0
  (0, 21)	0
  (0, 22)	0
  (0, 23)	0
  (0, 24)	0
  (0, 25)	0
  :	:
  (3016, 2945)	0
  (3016, 2946)	3
  (3016, 2947)	0
  (3016, 2948)	0
  (3016, 2949)	0
  (3016, 2950)	0
  (3016, 2951)	0
  (3016, 2952)	0
  (3016, 2953)	0
  (3016, 2954)	0
  (3016, 2955)	0
  (3016, 2956)	0
  (3016, 2957)	3
  (3016, 2958)	0
  (3016, 2959)	14
  (3016, 2960)	0
  (3016, 2961)	24
  (3016, 2962)	0
  (3016, 2963)	0
  (3016, 2964)	0
  (3016, 2965)	0
  (3016, 2966)	0
  (3016, 2967)	0
  (3016, 2968)	0
  (3016, 2969)	999


In [16]:
spec_clust_csv = SpectralClustering(n_clusters = 3, affinity='nearest_neighbors').fit(df_csv_data)

In [17]:
spec_clust_csv.labels_

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 0, 2, 1,
       1, 1, 1, 2, 2, 2, 2, 1, 2, 0, 0, 0, 2, 1, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 2, 0, 1])

In [18]:
np.set_printoptions(threshold=np.inf)
spec_clust = SpectralClustering(n_clusters = 4, affinity='precomputed').fit(adj_mat)
spec_clust.labels_

C:\Users\49171\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\manifold\_spectral_embedding.py:234: UserWarning: Array is not symmetric, and will be converted to symmetric by average with its transpose.
  adjacency = check_symmetric(adjacency)
C:\Users\49171\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\manifold\_spectral_embedding.py:260: UserWarning: Graph is not fully connected, spectral embedding may not work as expected.
  warnings.warn(


array([3, 2, 0, 2, 3, 2, 2, 3, 0, 2, 2, 0, 1, 1, 3, 2, 2, 2, 3, 3, 2, 0,
       1, 1, 2, 0, 1, 3, 2, 2, 0, 0, 0, 3, 0, 2, 0, 3, 3, 3, 2, 3, 1, 1,
       2, 2, 1, 2, 3, 1, 2, 2, 0, 3, 2, 2, 1, 2, 2, 0, 2, 3, 0, 2, 2, 3,
       2, 2, 2, 3, 3, 0, 2, 2, 2, 2, 2, 2, 0, 3, 2, 2, 3, 3, 0, 2, 2, 3,
       0, 0, 2, 3, 2, 2, 3, 3, 1, 3, 1, 3, 1, 1, 3, 0, 3, 3, 2, 0, 3, 2,
       2, 2, 2, 3, 2, 2, 2, 2, 3, 2, 0, 1, 2, 2, 0, 1, 0, 2, 0, 3, 2, 0,
       3, 2, 3, 0, 2, 1, 2, 0, 2, 1, 0, 2, 2, 1, 2, 1, 2, 2, 2, 0, 1, 2,
       3, 3, 2, 2, 3, 2, 2, 2, 3, 2, 3, 1, 3, 2, 0, 1, 1, 1, 2, 2, 3, 3,
       2, 2, 0, 2, 2, 2, 1, 0, 2, 0, 2, 2, 3, 2, 2, 0, 2, 2, 2, 2, 3, 0,
       2, 2, 0, 0, 2, 0, 3, 2, 2, 2, 0, 1, 2, 2, 2, 2, 2, 2, 2, 0, 3, 2,
       2, 2, 3, 0, 0, 0, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 3, 3, 2, 3, 0, 0,
       2, 2, 0, 3, 3, 2, 2, 0, 0, 2, 1, 2, 1, 2, 1, 2, 2, 2, 1, 2, 1, 2,
       0, 2, 3, 1, 2, 2, 2, 3, 2, 2, 2, 2, 1, 2, 1, 0, 3, 2, 3, 3, 1, 0,
       3, 2, 2, 3, 0, 3, 2, 0, 2, 2, 2, 2, 2, 2, 2,